name: Push image to ghcr.io

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          docker build -t ghcr.io/voidcontests/runner:$SHORT_SHA \
            -t ghcr.io/voidcontests/runner:$BRANCH_NAME .

          if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "dev" ]]; then
            docker push ghcr.io/voidcontests/runner:$SHORT_SHA
          fi

          docker push ghcr.io/voidcontests/runner:$BRANCH_NAME

          if [[ "$BRANCH_NAME" == "master" ]]; then
            docker tag ghcr.io/voidcontests/runner:$SHORT_SHA ghcr.io/voidcontests/runner:latest
            docker push ghcr.io/voidcontests/runner:latest
          fi
