name: Push image to ghcr.io

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/voidcontests/runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        run: curl -sSL https://raw.githubusercontent.com/voidcontests/infra/refs/heads/master/push-image.sh | bash -s -- $IMAGE_NAME
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
